{{- define "local-ai.pvc" -}}
{{- $rootContext := .rootContext -}}
{{- $pvcObject := .object -}}

{{- $labels := merge
  ($pvcObject.labels | default dict)
  (include "local-ai.labels" $rootContext | fromYaml)
-}}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcObject.name }}
  {{- with $labels }}
  labels: {{- toYaml . | nindent 4 -}}
  {{- end }}
  {{- with $pvcObject.annotations }}
  annotations: {{- toYaml . | nindent 4 -}}
  {{- end }}
spec:
  {{- with required "accessModes is required for PVC" $pvcObject.accessModes }}
  accessModes: {{- toYaml . | nindent 4 -}}
  {{- end }}
  resources:
    requests:
      storage: {{ required "size is required for PVC" $pvcObject.size | quote }}
  {{- if $pvcObject.storageClass }}
  storageClassName: {{ if (eq "-" $pvcObject.storageClass) }}""{{- else }}{{ $pvcObject.storageClass | quote }}{{- end }}
  {{- end }}
{{- end -}}

