{{- if .Values.modelsVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "local-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if .Values.modelsVolume.pvc.storageClassName }}
  storageClassName: {{ .Values.modelsVolume.pvc.storageClassName }}
  {{- end }}
  accessModes: {{ .Values.modelsVolume.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.modelsVolume.pvc.size | quote }}
{{- end }}